# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\patientsearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaPtntLookup(object):
    def setupUi(self, diaPtntLookup):
        diaPtntLookup.setObjectName("diaPtntLookup")
        diaPtntLookup.resize(800, 1200)
        self.widget = QtWidgets.QWidget(diaPtntLookup)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(190, 170, 600, 100))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(700, 70, 111, 41))
        self.logout.setObjectName("logout")
        self.labelLastName = QtWidgets.QLabel(self.widget)
        self.labelLastName.setGeometry(QtCore.QRect(160, 310, 201, 51))
        self.labelLastName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelLastName.setObjectName("labelLastName")
        self.labelFirstName = QtWidgets.QLabel(self.widget)
        self.labelFirstName.setGeometry(QtCore.QRect(160, 390, 201, 51))
        self.labelFirstName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelFirstName.setObjectName("labelFirstName")
        self.lastField = QtWidgets.QLineEdit(self.widget)
        self.lastField.setGeometry(QtCore.QRect(390, 320, 151, 22))
        self.lastField.setObjectName("lastField")
        self.firstField = QtWidgets.QLineEdit(self.widget)
        self.firstField.setGeometry(QtCore.QRect(390, 400, 151, 21))
        self.firstField.setObjectName("firstField")
        self.search = QtWidgets.QPushButton(self.widget)
        self.search.setGeometry(QtCore.QRect(302, 530, 151, 35))
        self.search.setObjectName("search")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(230, 490, 291, 31))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";color:rgb(255,0,0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.resultsTable = QtWidgets.QTableWidget(self.widget)
        self.resultsTable.setGeometry(QtCore.QRect(0, 0, 641, 691))
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)

        self.retranslateUi(diaPtntLookup)
        QtCore.QMetaObject.connectSlotsByName(diaPtntLookup)

    def retranslateUi(self, diaPtntLookup):
        _translate = QtCore.QCoreApplication.translate
        diaPtntLookup.setWindowTitle(_translate("diaPtntLookup", "Dialog"))
        self.label.setText(_translate("diaPtntLookup", "<html><head/><body><p><span style=\" font-size:26pt;\">Patient Lookup</span></p></body></html>"))
        self.logout.setText(_translate("diaPtntLookup", "Logout"))
        self.labelLastName.setText(_translate("diaPtntLookup", "<html><head/><body><p><span style=\" font-size:10pt;\">Last Name:</span></p></body></html>"))
        self.labelFirstName.setText(_translate("diaPtntLookup", "<html><head/><body><p><span style=\" font-size:10pt;\">First Name:</span></p></body></html>"))
        self.search.setText(_translate("diaPtntLookup", "Search"))
