# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\ApplicationScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1200, 800))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(300, 120, 600, 61))
        self.label.setStyleSheet("font: 75 26pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(300, 200, 600, 41))
        self.label_2.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(250, 260, 700, 400))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(20)
        self.gridLayout.setObjectName("gridLayout")
        self.PatientSearch = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.PatientSearch.setMinimumSize(QtCore.QSize(280, 130))
        self.PatientSearch.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.PatientSearch.setObjectName("PatientSearch")
        self.gridLayout.addWidget(self.PatientSearch, 0, 0, 1, 1)
        self.RegisterPatient = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RegisterPatient.setMinimumSize(QtCore.QSize(280, 130))
        self.RegisterPatient.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.RegisterPatient.setObjectName("RegisterPatient")
        self.gridLayout.addWidget(self.RegisterPatient, 0, 1, 1, 1)
        self.RegisterAdmission = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.RegisterAdmission.setMinimumSize(QtCore.QSize(280, 130))
        self.RegisterAdmission.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.RegisterAdmission.setObjectName("RegisterAdmission")
        self.gridLayout.addWidget(self.RegisterAdmission, 1, 0, 1, 1)
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(1050, 70, 120, 50))
        self.logout.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";")
        self.logout.setObjectName("logout")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hospital Management System"))
        self.label.setText(_translate("Dialog", "Hospital Management System"))
        self.label_2.setText(_translate("Dialog", "Select an Operation"))
        self.PatientSearch.setText(_translate("Dialog", "Patient Search"))
        self.RegisterPatient.setText(_translate("Dialog", "Register Patient"))
        self.RegisterAdmission.setText(_translate("Dialog", "Register Admission"))
        self.logout.setText(_translate("Dialog", "Logout"))
