# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\login1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 1200)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.labelUser = QtWidgets.QLabel(self.widget)
        self.labelUser.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelUser.setObjectName("labelUser")
        self.gridLayout_2.addWidget(self.labelUser, 1, 0, 1, 1)
        self.userField = QtWidgets.QLineEdit(self.widget)
        self.userField.setObjectName("userField")
        self.gridLayout_2.addWidget(self.userField, 1, 1, 1, 1)
        self.labelPass = QtWidgets.QLabel(self.widget)
        self.labelPass.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.labelPass.setObjectName("labelPass")
        self.gridLayout_2.addWidget(self.labelPass, 2, 0, 1, 1)
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setObjectName("passwordField")
        self.gridLayout_2.addWidget(self.passwordField, 2, 1, 1, 1)
        self.login = QtWidgets.QPushButton(self.widget)
        self.login.setStyleSheet("font: 16pt \"MS Shell Dlg 2\";")
        self.login.setObjectName("login")
        self.gridLayout_2.addWidget(self.login, 3, 1, 1, 1)
        self.errorMsg = QtWidgets.QLabel(self.widget)
        self.errorMsg.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";color:rgb(255, 0, 0)")
        self.errorMsg.setText("")
        self.errorMsg.setObjectName("errorMsg")
        self.gridLayout_2.addWidget(self.errorMsg, 4, 0, 1, 2)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:20pt;\">PIMS</span></p></body></html>"))
        self.labelUser.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Username:</span></p></body></html>"))
        self.labelPass.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:12pt;\">Password:</span></p></body></html>"))
        self.login.setText(_translate("Dialog", "Login"))
