# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\MainScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(50, 50, 50, 50)
        self.verticalLayout.setSpacing(40)

        self.label_3 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        sizePolicy.setHorizontalPolicy(QtWidgets.QSizePolicy.Expanding)
        
        self.label_3.setMinimumSize(QtCore.QSize(600, 100))
        self.label_3.setStyleSheet("font: bold 24pt \"MS Shell Dlg 2\"; color: #333333;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.enterApplication = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.enterApplication.sizePolicy().hasHeightForWidth())
        self.enterApplication.setSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        self.enterApplication.setMinimumSize(QtCore.QSize(500, 100))
        self.enterApplication.setMaximumSize(QtCore.QSize(16777215, 100))  # 16777215 = no limit
        self.enterApplication.setStyleSheet("QPushButton {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"    font: bold 10pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #d6d6d6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c0c0c0;\n"
"}")
        self.enterApplication.setObjectName("enterApplication")
        self.verticalLayout.addWidget(self.enterApplication, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, alignment=QtCore.Qt.AlignCenter)

        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1, alignment=QtCore.Qt.AlignCenter)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Hospital Management System"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Welcome to the Patient Information</p><p align=\"center\">Management System (PIMS)</p></body></html>"))
        self.enterApplication.setText(_translate("Dialog", "Enter Application"))
