# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\patientsearch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaPtntLookup(object):
    def setupUi(self, diaPtntLookup):
        diaPtntLookup.setObjectName("diaPtntLookup")
        diaPtntLookup.resize(800, 1200)
        self.widget = QtWidgets.QWidget(diaPtntLookup)
        self.widget.setGeometry(QtCore.QRect(0, -60, 800, 1200))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(190, 170, 401, 61))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(652, 70, 111, 41))
        self.logout.setObjectName("logout")
        self.backButton = QtWidgets.QPushButton(self.widget)
        self.backButton.setGeometry(QtCore.QRect(50, 70, 111, 41))
        self.backButton.setObjectName("backButton")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(250, 470, 291, 31))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";color:rgb(255,0,0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(170, 270, 441, 191))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.labelLastName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelLastName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelLastName.setObjectName("labelLastName")
        self.gridLayout.addWidget(self.labelLastName, 0, 0, 1, 1)
        self.lastField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lastField.setObjectName("lastField")
        self.gridLayout.addWidget(self.lastField, 0, 1, 1, 1)
        self.labelFirstName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelFirstName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelFirstName.setObjectName("labelFirstName")
        self.gridLayout.addWidget(self.labelFirstName, 1, 0, 1, 1)
        self.firstField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstField.setObjectName("firstField")
        self.gridLayout.addWidget(self.firstField, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.midField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.midField.setObjectName("midField")
        self.gridLayout.addWidget(self.midField, 2, 1, 1, 1)
        self.lastBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.lastBox.setObjectName("lastBox")
        self.gridLayout.addWidget(self.lastBox, 0, 2, 1, 1)
        self.firstBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.firstBox.setObjectName("firstBox")
        self.gridLayout.addWidget(self.firstBox, 1, 2, 1, 1)
        self.search = QtWidgets.QPushButton(self.widget)
        self.search.setGeometry(QtCore.QRect(340, 510, 116, 28))
        self.search.setObjectName("search")
        self.resultsTable = QtWidgets.QTableWidget(self.widget)
        self.resultsTable.setGeometry(QtCore.QRect(50, 550, 700, 500))
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)

        self.retranslateUi(diaPtntLookup)
        QtCore.QMetaObject.connectSlotsByName(diaPtntLookup)

    def retranslateUi(self, diaPtntLookup):
        _translate = QtCore.QCoreApplication.translate
        diaPtntLookup.setWindowTitle(_translate("diaPtntLookup", "Patient Search"))
        self.label.setText(_translate("diaPtntLookup", "Patient Lookup"))
        self.logout.setText(_translate("diaPtntLookup", "Logout"))
        self.backButton.setText(_translate("diaPtntLookup", "Back"))
        self.labelLastName.setText(_translate("diaPtntLookup", "Last Name:"))
        self.labelFirstName.setText(_translate("diaPtntLookup", "First Name:"))
        self.label_2.setText(_translate("diaPtntLookup", "Middle Name:"))
        self.lastBox.setText(_translate("diaPtntLookup", "Partial Search"))
        self.firstBox.setText(_translate("diaPtntLookup", "Partial Search"))
        self.search.setText(_translate("diaPtntLookup", "Search"))
