# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\registerlocation.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 700)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 700))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(200, 70, 401, 61))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.backTo = QtWidgets.QPushButton(self.widget)
        self.backTo.setGeometry(QtCore.QRect(50, 70, 120, 40))
        self.backTo.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.backTo.setObjectName("backTo")
        self.formLayoutWidget = QtWidgets.QWidget(self.widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(100, 180, 600, 350))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.facilityField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.facilityField.setMinimumSize(QtCore.QSize(0, 35))
        self.facilityField.setObjectName("facilityField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.facilityField)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.floorField = QtWidgets.QSpinBox(self.formLayoutWidget)
        self.floorField.setMinimumSize(QtCore.QSize(0, 35))
        self.floorField.setMinimum(1)
        self.floorField.setMaximum(99)
        self.floorField.setObjectName("floorField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.floorField)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.roomField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.roomField.setMinimumSize(QtCore.QSize(0, 35))
        self.roomField.setObjectName("roomField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.roomField)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.bedField = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.bedField.setMinimumSize(QtCore.QSize(0, 35))
        self.bedField.setObjectName("bedField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.bedField)
        self.addLocation = QtWidgets.QPushButton(self.widget)
        self.addLocation.setGeometry(QtCore.QRect(300, 550, 200, 50))
        self.addLocation.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.addLocation.setObjectName("addLocation")
        self.errorMsg = QtWidgets.QLabel(self.widget)
        self.errorMsg.setGeometry(QtCore.QRect(100, 610, 600, 40))
        self.errorMsg.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";color:rgb(255,0,0)")
        self.errorMsg.setText("")
        self.errorMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMsg.setWordWrap(True)
        self.errorMsg.setObjectName("errorMsg")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Register Location"))
        self.label.setText(_translate("Dialog", "Register Location"))
        self.backTo.setText(_translate("Dialog", "Back"))
        self.label_2.setText(_translate("Dialog", "Facility:"))
        self.label_3.setText(_translate("Dialog", "Floor:"))
        self.label_4.setText(_translate("Dialog", "Room Number:"))
        self.label_5.setText(_translate("Dialog", "Bed Number:"))
        self.addLocation.setText(_translate("Dialog", "Add Location"))
