# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\setup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1200, 800)
        Dialog.setMinimumSize(QtCore.QSize(1200, 800))
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(600, 80))
        self.label.setStyleSheet("font: bold 28pt \"MS Shell Dlg 2\"; color: #333333; padding-bottom: 20px;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter)
        self.infoLabel = QtWidgets.QLabel(self.widget)
        self.infoLabel.setMinimumSize(QtCore.QSize(700, 80))
        self.infoLabel.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; color: #333333;")
        self.infoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.infoLabel.setWordWrap(True)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel, 0, QtCore.Qt.AlignHCenter)
        self.formLayout = QtWidgets.QGridLayout()
        self.formLayout.setContentsMargins(300, -1, 300, -1)
        self.formLayout.setHorizontalSpacing(15)
        self.formLayout.setVerticalSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.labelFirstName = QtWidgets.QLabel(self.widget)
        self.labelFirstName.setMinimumSize(QtCore.QSize(150, 40))
        self.labelFirstName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding-right: 10px;")
        self.labelFirstName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFirstName.setObjectName("labelFirstName")
        self.formLayout.addWidget(self.labelFirstName, 0, 0, 1, 1)
        self.firstNameField = QtWidgets.QLineEdit(self.widget)
        self.firstNameField.setMinimumSize(QtCore.QSize(0, 40))
        self.firstNameField.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; border: 1px solid #aaa; border-radius: 4px; padding: 5px; background-color: white;")
        self.firstNameField.setObjectName("firstNameField")
        self.formLayout.addWidget(self.firstNameField, 0, 1, 1, 1)
        self.labelLastName = QtWidgets.QLabel(self.widget)
        self.labelLastName.setMinimumSize(QtCore.QSize(150, 40))
        self.labelLastName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding-right: 10px;")
        self.labelLastName.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLastName.setObjectName("labelLastName")
        self.formLayout.addWidget(self.labelLastName, 1, 0, 1, 1)
        self.lastNameField = QtWidgets.QLineEdit(self.widget)
        self.lastNameField.setMinimumSize(QtCore.QSize(0, 40))
        self.lastNameField.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; border: 1px solid #aaa; border-radius: 4px; padding: 5px; background-color: white;")
        self.lastNameField.setObjectName("lastNameField")
        self.formLayout.addWidget(self.lastNameField, 1, 1, 1, 1)
        self.labelUsername = QtWidgets.QLabel(self.widget)
        self.labelUsername.setMinimumSize(QtCore.QSize(150, 40))
        self.labelUsername.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding-right: 10px;")
        self.labelUsername.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelUsername.setObjectName("labelUsername")
        self.formLayout.addWidget(self.labelUsername, 2, 0, 1, 1)
        self.usernameField = QtWidgets.QLineEdit(self.widget)
        self.usernameField.setMinimumSize(QtCore.QSize(0, 40))
        self.usernameField.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; border: 1px solid #aaa; border-radius: 4px; padding: 5px; background-color: white;")
        self.usernameField.setObjectName("usernameField")
        self.formLayout.addWidget(self.usernameField, 2, 1, 1, 1)
        self.labelPassword = QtWidgets.QLabel(self.widget)
        self.labelPassword.setMinimumSize(QtCore.QSize(150, 40))
        self.labelPassword.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding-right: 10px;")
        self.labelPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelPassword.setObjectName("labelPassword")
        self.formLayout.addWidget(self.labelPassword, 3, 0, 1, 1)
        self.passwordField = QtWidgets.QLineEdit(self.widget)
        self.passwordField.setMinimumSize(QtCore.QSize(0, 40))
        self.passwordField.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; border: 1px solid #aaa; border-radius: 4px; padding: 5px; background-color: white;")
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.formLayout.addWidget(self.passwordField, 3, 1, 1, 1)
        self.labelConfirmPassword = QtWidgets.QLabel(self.widget)
        self.labelConfirmPassword.setMinimumSize(QtCore.QSize(150, 40))
        self.labelConfirmPassword.setStyleSheet("font: 14pt \"MS Shell Dlg 2\"; padding-right: 10px;")
        self.labelConfirmPassword.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelConfirmPassword.setObjectName("labelConfirmPassword")
        self.formLayout.addWidget(self.labelConfirmPassword, 4, 0, 1, 1)
        self.confirmPasswordField = QtWidgets.QLineEdit(self.widget)
        self.confirmPasswordField.setMinimumSize(QtCore.QSize(0, 40))
        self.confirmPasswordField.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; border: 1px solid #aaa; border-radius: 4px; padding: 5px; background-color: white;")
        self.confirmPasswordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.confirmPasswordField.setObjectName("confirmPasswordField")
        self.formLayout.addWidget(self.confirmPasswordField, 4, 1, 1, 1)
        self.verticalLayout.addLayout(self.formLayout)
        self.initializeButton = QtWidgets.QPushButton(self.widget)
        self.initializeButton.setMinimumSize(QtCore.QSize(250, 50))
        self.initializeButton.setStyleSheet("QPushButton {\n"
"    background-color: #e0e0e0;\n"
"    color: black;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 4px;\n"
"    padding: 10px;\n"
"    font: bold 14pt \"MS Shell Dlg 2\";\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #d6d6d6;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #c0c0c0;\n"
"}")
        self.initializeButton.setObjectName("initializeButton")
        self.verticalLayout.addWidget(self.initializeButton, 0, QtCore.Qt.AlignHCenter)
        self.errorMsg = QtWidgets.QLabel(self.widget)
        self.errorMsg.setMinimumSize(QtCore.QSize(600, 50))
        self.errorMsg.setStyleSheet("font: 12pt \"MS Shell Dlg 2\"; color: rgb(255, 0, 0);")
        self.errorMsg.setText("")
        self.errorMsg.setAlignment(QtCore.Qt.AlignCenter)
        self.errorMsg.setWordWrap(True)
        self.errorMsg.setObjectName("errorMsg")
        self.verticalLayout.addWidget(self.errorMsg, 0, QtCore.Qt.AlignHCenter)
        self.progressBar = QtWidgets.QProgressBar(self.widget)
        self.progressBar.setMinimumSize(QtCore.QSize(500, 30))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(True)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar, 0, QtCore.Qt.AlignHCenter)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.firstNameField, self.lastNameField)
        Dialog.setTabOrder(self.lastNameField, self.usernameField)
        Dialog.setTabOrder(self.usernameField, self.passwordField)
        Dialog.setTabOrder(self.passwordField, self.confirmPasswordField)
        Dialog.setTabOrder(self.confirmPasswordField, self.initializeButton)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Initialize Database - Hospital Management System"))
        self.label.setText(_translate("Dialog", "Database Initialization"))
        self.infoLabel.setText(_translate("Dialog", "<html><head/><body><p align=\"center\">Create Administrator To Initialize Database<"))
        self.labelFirstName.setText(_translate("Dialog", "First Name:"))
        self.labelLastName.setText(_translate("Dialog", "Last Name:"))
        self.labelUsername.setText(_translate("Dialog", "Username:"))
        self.labelPassword.setText(_translate("Dialog", "Password:"))
        self.labelConfirmPassword.setText(_translate("Dialog", "Confirm Password:"))
        self.initializeButton.setText(_translate("Dialog", "Initialize Database"))
