# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\pitch\OneDrive\Documents\GitHub\CS499\stafflookup.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_diaStaffLookup(object):
    def setupUi(self, diaStaffLookup):
        diaStaffLookup.setObjectName("diaStaffLookup")
        diaStaffLookup.resize(800, 1200)
        self.widget = QtWidgets.QWidget(diaStaffLookup)
        self.widget.setGeometry(QtCore.QRect(0, -20, 800, 1200))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:1, y1:0.982409, x2:1, y2:0, stop:0 rgba(0, 170, 255, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(210, 200, 401, 71))
        self.label.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.logout = QtWidgets.QPushButton(self.widget)
        self.logout.setGeometry(QtCore.QRect(652, 70, 111, 41))
        self.logout.setObjectName("logout")
        self.backButton = QtWidgets.QPushButton(self.widget)
        self.backButton.setGeometry(QtCore.QRect(50, 70, 111, 41))
        self.backButton.setObjectName("backButton")
        self.search = QtWidgets.QPushButton(self.widget)
        self.search.setGeometry(QtCore.QRect(300, 490, 151, 28))
        self.search.setObjectName("search")
        self.error = QtWidgets.QLabel(self.widget)
        self.error.setGeometry(QtCore.QRect(230, 450, 291, 31))
        self.error.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";color:rgb(255,0,0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.gridLayoutWidget = QtWidgets.QWidget(self.widget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(180, 290, 401, 151))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lastField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lastField.setObjectName("lastField")
        self.gridLayout.addWidget(self.lastField, 0, 1, 1, 1)
        self.firstField = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.firstField.setObjectName("firstField")
        self.gridLayout.addWidget(self.firstField, 1, 1, 1, 1)
        self.labelFirstName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelFirstName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelFirstName.setObjectName("labelFirstName")
        self.gridLayout.addWidget(self.labelFirstName, 1, 0, 1, 1)
        self.labelLastName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.labelLastName.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.labelLastName.setObjectName("labelLastName")
        self.gridLayout.addWidget(self.labelLastName, 0, 0, 1, 1)
        self.lastBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.lastBox.setObjectName("lastBox")
        self.gridLayout.addWidget(self.lastBox, 0, 2, 1, 1)
        self.firstBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        self.firstBox.setObjectName("firstBox")
        self.gridLayout.addWidget(self.firstBox, 1, 2, 1, 1)
        self.resultsTable = QtWidgets.QTableWidget(self.widget)
        self.resultsTable.setGeometry(QtCore.QRect(50, 550, 700, 500))
        self.resultsTable.setObjectName("resultsTable")
        self.resultsTable.setColumnCount(0)
        self.resultsTable.setRowCount(0)

        self.retranslateUi(diaStaffLookup)
        QtCore.QMetaObject.connectSlotsByName(diaStaffLookup)

    def retranslateUi(self, diaStaffLookup):
        _translate = QtCore.QCoreApplication.translate
        diaStaffLookup.setWindowTitle(_translate("diaStaffLookup", "Staff Lookup"))
        self.label.setText(_translate("diaStaffLookup", "Staff Lookup"))
        self.logout.setText(_translate("diaStaffLookup", "Logout"))
        self.backButton.setText(_translate("diaStaffLookup", "Back"))
        self.search.setText(_translate("diaStaffLookup", "Search"))
        self.labelFirstName.setText(_translate("diaStaffLookup", "First Name:"))
        self.labelLastName.setText(_translate("diaStaffLookup", "Last Name:"))
        self.lastBox.setText(_translate("diaStaffLookup", "Partial Search"))
        self.firstBox.setText(_translate("diaStaffLookup", "Partial Search"))
